---
- name: Add key for haproxy external repository
  ansible.builtin.get_url:
    url: http://ppa.launchpad.net/vbernat/haproxy-2.7/ubuntu/dists/focal/Release.gpg
    dest: /etc/apt/trusted.gpg.d/haproxy.asc
  tags: [install]
  when: repository_source == 'external'

- name: Add source repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/trusted.gpg.d/haproxy.asc] {{ haproxy_repository }}"
    state: present

# - name: Add repository
#   ansible.builtin.apt_repository:
#     repo: "{{ haproxy_repository }}"
#     state: present
#   when: repository_source == 'external'


- name: Add repository from nexus(when var repository_source is 'internal')
  ansible.builtin.apt_repository:
    repo: "{{ haproxy_proxy_repository }}"
    state: present
  when: repository_source == 'internal'

- name: Install haproxy
  ansible.builtin.apt:
    name: "{{ haproxy_packet_name }}={{ haproxy_version }}"
    state: present
    update_cache: true
  notify:
    - restart haproxy

- name: Setting haproxy config
  ansible.builtin.template:
    src: etc/haproxy/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
#    validate: "haproxy -f %s -c"
#  notify:
#    - reload haproxy
