---

- debug:
    msg: "Gateway to haproxy: {{ keepalived_lb_vip }}:{{ch_frontend_port }}"
    
- name: Add key for haproxy from external repository
  ansible.builtin.apt_key:
    keyserver: "{{ haproxy_keyserver }}"
    id: "{{ haproxy_repo_key_id }}"
  tags: [haproxy_install]
  when: repository_source == 'external'

# - name: Add key for haproxy from nexus repository
#   ansible.builtin.apt_key:
#     url: "{{ haproxy_proxy_repo_key }}"
#   tags: [haproxy_install]
#   when: repository_source == 'internal'

- name: Add key for haproxy from nexus repository
  ansible.builtin.get_url:
    url: "{{ haproxy_proxy_repo_key }}"
    dest: /etc/apt/trusted.gpg.d/haproxy.asc
  tags: [haproxy_install]
  when: repository_source == 'internal'

- name: Add source repository into sources list
  ansible.builtin.apt_repository:
    repo: "{{ haproxy_repository }}"
    state: present
  when: repository_source == 'external'
  tags: [haproxy_install]

- name: Add repository from nexus(when var repository_source is 'internal')
  ansible.builtin.apt_repository:
    repo: "{{ haproxy_proxy_repository }}"
    state: present
  when: repository_source == 'internal'
  tags: [haproxy_install]
  
- name: Install haproxy
  ansible.builtin.apt:
    name: "{{ haproxy_packet_name }}={{ haproxy_version }}"
    state: present
    update_cache: true
  tags: [haproxy_install]

- name: Setting haproxy config
  ansible.builtin.template:
    src: etc/haproxy/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    validate: "haproxy -f %s -c"
  tags: [haproxy_config]
  notify:
    - reload haproxy

- name: Ensure haproxy is started and enabled on boot.
  service:
    name: haproxy
    state: started
    enabled: true
  tags: [haproxy_config]

- name: Flush handlers
  meta: flush_handlers