---
# tasks file for clickhouse

- name: 'Include OS Family Specific Variables'
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - 'empty.yml'
      paths:
        - 'vars'
  tags: [always]

- include_tasks: precheck.yml
  tags: [always]

- include_tasks: params.yml
  tags: [always]

- include_tasks:
    file: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "install/{{ ansible_pkg_mgr }}.yml"
        - 'empty.yml'
  when: not clickhouse_remove|bool
  tags: [clickhouse_install]

- include_tasks: 
    file: configure/sys.yml
  when: not clickhouse_remove|bool
  tags: [clickhouse_config]

- name: "Notify Handlers Now"
  tags: [always]
  meta: flush_handlers

- include_tasks: service.yml
  tags: [clickhouse_install]

- name: "Wait for Clickhouse Server to Become Ready"
  wait_for:
    host: "{{ ansible_default_ipv4.address }}"
    port: "{{ clickhouse_tcp_port }}"
    delay: "{{ clickhouse_ready_delay }}"
  tags: [always]  
  when: not clickhouse_remove|bool

- include_tasks:
    file: configure/db.yml
  when: not clickhouse_remove|bool
  tags: [clickhouse_config]

- include_tasks:
    file: configure/dict.yml
  when: not clickhouse_remove|bool
  tags: [clickhouse_config]

- include_tasks:
    file: remove.yml
  when: clickhouse_remove|bool
  tags: [remove]