---
# in future
# - name: Enable ipv4 forvarding
#   ansible.builtin.shell: sysctl -w net.ipv4.ip_forward=1

- name: Add repository from nexus(when var repository_source is 'internal')
  apt_repository:
    repo: "{{ apt_proxy_repository }}"
    state: present
  when: repository_source == 'internal'
  tags: [keepalived_install]

- name: Ensure keepalived package is installed
  ansible.builtin.apt:
    name: "keepalived=1:{{ keepalived_lb_version }}"
    state: present
    update_cache: true
  tags: [keepalived_install]
  notify:
    - restart keepalived
  when:
    - not ansible_check_mode
    - keepalived_lb_version != 'latest'

- name: Ensure keepalived latest version is installed
  ansible.builtin.apt:
    name: "keepalived={{ keepalived_lb_version }}"
    state: present
    update_cache: true
  tags: [keepalived_install]
  notify:
    - restart keepalived
  when:
    - not ansible_check_mode
    - keepalived_lb_version == 'latest'

- name: Ensure keepalived script direcotry is created
  file:
    path: /etc/keepalived/scripts/
    state: directory
    owner: root
    group: root
    mode: 0755
  when:
    - keepalived_lb_enable_nat_switch | bool
  tags: [keepalived_config]

- name: Ensure keepalived haproxy-service-check script is removed
  file:
    path: /usr/local/bin/haproxy-service-check.sh
    state: absent
  tags: [keepalived_config]

- name: Ensure keepalived nat_switch script is templated
  template:
    src: etc/keepalived/scripts/nat-switch.j2
    dest: /etc/keepalived/scripts/nat-switch
    mode: "a+x"
  when:
    - keepalived_lb_enable_nat_switch | bool
  tags: [keepalived_config]

- name: Ensure keepalived nat_switch script is removed
  file:
    path: /etc/keepalived/scripts/nat-switch
    state: absent
  when:
    - not keepalived_lb_enable_nat_switch
  tags: [keepalived_config]

- name: Ensure keepalived main config is templated
  template:
    src: etc/keepalived/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - "{{ keepalived_systemd_notify }} keepalived"
  tags: [keepalived_config]

- name: Ensure keepalived is enabled
  systemd:
    name: keepalived
    enabled: true
    daemon_reload: true
    state: started
  when:
    - not ansible_check_mode
  tags: [keepalived_config]

- name: Copy script for installing keepalived exporter
  become: true
  ansible.builtin.copy:
    src: templates/etc/keepalived/scripts/keepalived_exporter_install.sh
    dest: /tmp/keepalived_exporter_install.sh
    owner: root
    group: root
    mode: 0755
  tags: [keepalived_exporter]
  when: keepalived_exporter|bool

- name: Run script [Instaling]
  become: true
  ansible.builtin.shell: /tmp/keepalived_exporter_install.sh
  tags: [keepalived_exporter]
  register: script
  when: keepalived_exporter|bool
- debug: 
    var: script.stdout_lines
  when: keepalived_exporter|bool
  tags: [keepalived_exporter]