variables: 
  AIND: git-registry.service.t1-cloud.ru/sre/docker/ansible:${ANSIBLE_TAG}
  ANSIBLE_TAG: latest
  ANSIBLE_FORCE_COLOR: 'true'
  DEPLOY_ENV: 't1-p1'

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: $CI_COMMIT_TAG
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

stages:
#  - ansible_lint
  - check_mode
  - zookeeper
  - clickhouse
  - haproxy_lb
#  - debug,check_replication,check_vars,check_status

.vault: &vault
  - export VAULT_ADDR=${VAULT_ADDR}
  - export VAULT_TOKEN=${VAULT_TOKEN}
  - vault status
  - pip3 install hvac

.ssh: &ssh
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - eval $(ssh-agent -s)
  - chmod 400 "$SRE_ADMIN_KEY"
  - ssh-add "$SRE_ADMIN_KEY"
  - cp "$SSH_KNOWN_HOSTS" ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
#  - ssh-keyscan 10.13.248.51 10.13.248.52 10.13.248.53

before_script:
  - ansible -m debug -a 'var=ansible_playbook_python' localhost
  - *ssh
  - date
  - *vault

check_all_roles:
  image: ${AIND}
  stage: check_mode
  script:
    - ansible-playbook -i inventories/${DEPLOY_ENV}/hosts clickhouse_infra.yml -u ${SSH_LOGIN} -e VAULT_ADDR=${VAULT_ADDR} -e "VAULT_TOKEN=${VAULT_TOKEN}" --check -vv --diff
  allow_failure: true

################ Deploy HA Clickhouse cluster ####################

.deploy:
  image: ${AIND}
  script:
    - ansible-playbook -i inventories/${DEPLOY_ENV}/hosts clickhouse_infra.yml -u ${SSH_LOGIN} --tags=${ROLE_TAGS} -e VAULT_ADDR=${VAULT_ADDR} -e "VAULT_TOKEN=${VAULT_TOKEN}" --diff
  allow_failure: false

zookeeper_install:
  extends: .deploy
  stage: zookeeper
  variables:
    ROLE_TAGS: zookeeper_install

zookeeper_config:
  extends: .deploy
  stage: zookeeper
  variables:
    ROLE_TAGS: zookeeper_config

clickhouse_install:
  extends: .deploy
  stage: clickhouse
  variables:
    ROLE_TAGS: clickhouse_install

clickhouse_config:
  extends: .deploy
  stage: clickhouse
  variables:
    ROLE_TAGS: clickhouse_config

clickhouse_remove:
  extends: .deploy
  stage: clickhouse
  variables:
    ROLE_TAGS: remove
  only:
    variables:
    - $clickhouse_remove == "true"
  
haproxy_install:
  extends: .deploy
  stage: haproxy_lb
  variables:
    ROLE_TAGS: haproxy_install

keepalived_install:
  extends: .deploy
  stage: haproxy_lb
  variables:
    ROLE_TAGS: keepalived_install