variables: 
  AIND: git-registry.service.t1-cloud.ru/sre/docker/ansible:${ANSIBLE_TAG}
  ANSIBLE_TAG: latest
  ANSIBLE_FORCE_COLOR: 'true'
  DEPLOY_ENV: 't1-p1'
  ROLE_TAGS: 'all'
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: $CI_COMMIT_TAG
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

stages:
  - check_mode
  - test
  - zookeeper
  - clickhouse
  - haproxy
  - keepalived

.vault: &vault
  - export VAULT_ADDR=${VAULT_ADDR}
  - export VAULT_TOKEN=${VAULT_TOKEN}
  - vault status

.ssh: &ssh
  - mkdir -p ~/.ssh
  - touch ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - chmod 700 ~/.ssh
  - eval $(ssh-agent -s)
  - chmod 400 "$SRE_ADMIN_KEY"
  - ssh-add "$SRE_ADMIN_KEY"
#  - cp "$SSH_KNOWN_HOSTS" ~/.ssh/known_hosts
  - ssh-keyscan 10.13.248.51 10.13.248.52 10.13.248.53 > ~/.ssh/known_hosts

before_script:
  - ansible -m debug -a 'var=ansible_playbook_python' localhost
  - *ssh
  - date
  - *vault

###### Check role #############################

.check_roles:
  image: ${AIND}
  stage: check_mode
  script:
    - ansible-playbook -i inventories/${DEPLOY_ENV}/hosts clickhouse_infra.yml -u ${SSH_LOGIN} --tags=${ROLE_TAGS} -e VAULT_ADDR=${VAULT_ADDR} -e "VAULT_TOKEN=${VAULT_TOKEN}" --check -vv --diff
  allow_failure: true
  when: manual

default config:
  extends: .check_roles

check zk config:
  extends: .check_roles
  variables:
    ROLE_TAGS: zookeeper_install,zookeeper_config
  # rules:
  #   - changes:
  #       - roles/zookeeper/*
  #       - inventories/t1-p1/group_vars/clickhouse/zookeeper.yml

check ch config:
  extends: .check_roles
  variables:
    ROLE_TAGS: clickhouse_install,clickhouse_config
  # rules:
  #   - changes:
  #       - roles/clickhouse/*
  #       - inventories/t1-p1/group_vars/clickhouse/clickhouse.yml

check haproxy config:
  extends: .check_roles
  variables:
    ROLE_TAGS: haproxy_install,haproxy_config
  # rules:
  #   - changes:
  #       - roles/haproxy/*
  #       - inventories/t1-p1/group_vars/clickhouse/haproxy.yml

check keepalived config:
  extends: .check_roles
  variables:
    ROLE_TAGS: keepalived_install,keepalived_config
  # rules:
  #   - changes:
  #       - roles/keepalived/*
  #       - inventories/t1-p1/group_vars/clickhouse/keepalived.yml


################ Deploy HA Clickhouse cluster ####################

.deploy:
  image: ${AIND}
  script:
    - ansible-playbook -i inventories/${DEPLOY_ENV}/hosts clickhouse_infra.yml -u ${SSH_LOGIN} --tags=${ROLE_TAGS} -e VAULT_ADDR=${VAULT_ADDR} -e "VAULT_TOKEN=${VAULT_TOKEN}" --diff
  allow_failure: false

.configure:
  image: ${AIND}
  script:
    - ansible-playbook -i inventories/${DEPLOY_ENV}/hosts clickhouse_infra.yml -u ${SSH_LOGIN} --tags=${ROLE_TAGS} -e VAULT_ADDR=${VAULT_ADDR} -e "VAULT_TOKEN=${VAULT_TOKEN}" --diff
  allow_failure: false

zookeeper:
  extends: .deploy
  stage: zookeeper
  variables:
    ROLE_TAGS: zookeeper_install,zookeeper_config
  needs: ["check zk config"]

clickhouse:
  extends: .deploy
  stage: clickhouse
  variables:
    ROLE_TAGS: clickhouse_install,clickhouse_config
  needs: ["check ch config"]

haproxy:
  extends: .deploy
  stage: haproxy
  variables:
    ROLE_TAGS: haproxy_install,haproxy_config
  needs: ["check haproxy config"]

keepalived:
  extends: .deploy
  stage: keepalived
  variables:
    ROLE_TAGS: keepalived_install,keepalived_config
  needs: ["check keepalived config"]

# clickhouse_remove:
#   extends: 
#   stage: clickhouse
#   variables:
#     ROLE_TAGS: remove
#   only:
#     variables:
#     - $clickhouse_remove == "true"