variables: 
  AIND: git-registry.service.t1-cloud.ru/sre/docker/ansible:${ANSIBLE_TAG}
  ANSIBLE_TAG: 2.10.7
  ANSIBLE_FORCE_COLOR: 'true'
  DEPLOY_ENV: 't1-p1'

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: $CI_COMMIT_TAG
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

stages:
#  - ansible_lint
  - check_mode
  - zookeeper
  - clickhouse
  - haproxy_lb
#  - debug,check_replication,check_vars,check_status

.vault: &vault
  - export VAULT_ADDR=${VAULT_ADDR}
  - export VAULT_TOKEN=${VAULT_TOKEN}
  - vault status


# .ssh: &ssh
#   - eval $(ssh-agent -s)
#   - touch id_rsa && chmod 600 id_rsa
#   - echo "${SRE_ADMIN_KEY}" > id_rsa
#   - ssh-add id_rsa  > /dev/null

.ssh: &ssh
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - echo -e "[all:vars]\nansible_user=${SSH_USER}\nansible_ssh_pass=$(vault kv get -field=${SSH_USER} deployment/prod/dns-as-a-service)\nansible_ssh_common_args='-o StrictHostKeyChecking=no'" >> ${HOSTS}


before_script:
  - *ssh
  - date

check_all_roles:
  image: ${AIND}
  stage: check_mode
  script:
    - ansible-playbook -i inventories/t1-p1/hosts clickhouse_infra.yml -u ${SSH_LOGIN} --check -vvvvv --diff
  allow_failure: true

################ Deploy HA Clickhouse cluster ####################

.deploy:
  image: ${AIND}
  script:
    - ansible-playbook -i inventories/${DEPLOY_ENV}/hosts clickhouse_infra.yml -u ${SSH_LOGIN} --tags=${ROLE_TAGS} --diff
  allow_failure: false

zookeeper_install:
  extends: .deploy
  stage: zookeeper
  variables:
    ROLE_TAGS: zookeeper_install

zookeeper_config:
  extends: .deploy
  stage: zookeeper
  variables:
    ROLE_TAGS: zookeeper_config

clickhouse_install:
  extends: .deploy
  stage: clickhouse
  variables:
    ROLE_TAGS: clickhouse_install

clickhouse_config:
  extends: .deploy
  stage: clickhouse
  variables:
    ROLE_TAGS: clickhouse_config

clickhouse_remove:
  extends: .deploy
  stage: clickhouse
  variables:
    ROLE_TAGS: remove
  only:
    variables:
    - $clickhouse_remove == "true"
  
haproxy_install:
  extends: .deploy
  stage: haproxy_lb
  variables:
    ROLE_TAGS: haproxy_install

keepalived_install:
  extends: .deploy
  stage: haproxy_lb
  variables:
    ROLE_TAGS: keepalived_install