variables: 
  AIND: git-registry.service.t1-cloud.ru/sre/docker/ansible:${ANSIBLE_TAG}
  ANSIBLE_TAG: latest
  ANSIBLE_FORCE_COLOR: 'true'
  ROLE_TAGS: 'all'

stages:
  - check_mode
  - general
  - zookeeper
  - clickhouse
  - haproxy
  - keepalived
  - exporters

.vault: &vault
  - export VAULT_ADDR=${VAULT_ADDR}
  - export VAULT_TOKEN=${VAULT_TOKEN}
  - vault status

.ssh: &ssh
  - mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
  - chmod 700 ~/.ssh && chmod 644 ~/.ssh/known_hosts
  - eval $(ssh-agent -s)
  - chmod 400 "$SRE_ADMIN_KEY"
  - ssh-add "$SRE_ADMIN_KEY"
#  - cp "$SSH_KNOWN_HOSTS" ~/.ssh/known_hosts
  - ssh-keyscan 10.13.247.51 10.13.247.52 10.13.247.53 > ~/.ssh/known_hosts

before_script:
  - ansible -m debug -a 'var=ansible_playbook_python' localhost
  - *ssh
  - date
  - *vault
  - pip install dnspython

###### Checking role #########################################################################

.check_roles:
  image: ${AIND}
  stage: check_mode
  script:
    - ansible-playbook -i inventories/${DEPLOY_ENV}/hosts clickhouse_infra.yml -u ${SSH_LOGIN} --tags=${ROLE_TAGS} -e VAULT_ADDR=${VAULT_ADDR} -e "VAULT_TOKEN=${VAULT_TOKEN}" --check -vv --diff
  allow_failure: true


###### Checking prod config ##################################################################

check general config:
  extends: .check_roles
  environment: prod
  variables:
    ROLE_TAGS: general_config,dns,ntp
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual
      
check zk config:
  extends: .check_roles
  environment: prod
  variables:
    ROLE_TAGS: zookeeper_install,zookeeper_config
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual

check ch config:
  extends: .check_roles
  environment: prod
  variables:
    ROLE_TAGS: clickhouse_install,clickhouse_config
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual

check haproxy config:
  extends: .check_roles
  environment: prod
  variables:
    ROLE_TAGS: haproxy_install,haproxy_config
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual

check keepalived config:
  extends: .check_roles
  environment: prod
  variables:
    ROLE_TAGS: keepalived_install,keepalived_config,keepalived_exporter
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual

###### Checking test config ##################################################################

check general test config:
  extends: .check_roles
  environment: prod
  variables:
    ROLE_TAGS: general_config,dns,ntp
  rules:
    - if: $CI_COMMIT_BRANCH == "test"
      when: manual

check zk test config:
  extends: .check_roles
  environment: prod
  variables:
    ROLE_TAGS: zookeeper_install,zookeeper_config
  rules:
    - if: $CI_COMMIT_BRANCH == "test"
      when: manual

check ch test config:
  extends: .check_roles
  environment: prod
  variables:
    ROLE_TAGS: clickhouse_install,clickhouse_config
  rules:
    - if: $CI_COMMIT_BRANCH == "test"
      when: manual

check haproxy test config:
  extends: .check_roles
  environment: prod
  variables:
    ROLE_TAGS: haproxy_install,haproxy_config
  rules:
    - if: $CI_COMMIT_BRANCH == "test"
      when: manual

check keepalived test config:
  extends: .check_roles
  environment: prod
  variables:
    ROLE_TAGS: keepalived_install,keepalived_config,keepalived_exporter
  rules:
    - if: $CI_COMMIT_BRANCH == "test"
      when: manual

################ Deploy HA Clickhouse cluster #######################################################

.deploy:
  image: ${AIND}
  script:
    - ansible-playbook -i inventories/${DEPLOY_ENV}/hosts clickhouse_infra.yml -u ${SSH_LOGIN} --tags=${ROLE_TAGS} -e VAULT_ADDR=${VAULT_ADDR} -e "VAULT_TOKEN=${VAULT_TOKEN}" --diff
  allow_failure: false

############### Deploy prod #########################################################################

general:
  extends: .deploy
  environment: prod
  stage: general
  variables:
    ROLE_TAGS: general_config,dns,ntp
  needs: ["check general config"]
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual

zookeeper:
  extends: .deploy
  environment: prod
  stage: zookeeper
  variables:
    ROLE_TAGS: zookeeper_install,zookeeper_config
  needs: ["check zk config"]
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual

clickhouse:
  extends: .deploy
  environment: prod
  stage: clickhouse
  variables:
    ROLE_TAGS: clickhouse_install,clickhouse_config
  needs: ["check ch config"]
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual

haproxy:
  extends: .deploy
  environment: prod
  stage: haproxy
  variables:
    ROLE_TAGS: haproxy_install,haproxy_config
  needs: ["check haproxy config"]
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual

keepalived:
  extends: .deploy
  environment: prod
  stage: keepalived
  variables:
    ROLE_TAGS: keepalived_install,keepalived_config,keepalived_exporter
  needs: ["check keepalived config"]
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual

############### Deploy test #########################################################################

deploy general in TEST:
  extends: .deploy
  environment: prod
  stage: general
  variables:
    ROLE_TAGS: general_config,dns,ntp
  needs: ["check general test config"]
  rules:
    - if: $CI_COMMIT_BRANCH == "test"
      when: manual

deploy zookeeper in TEST:
  extends: .deploy
  environment: prod
  stage: zookeeper
  variables:
    ROLE_TAGS: zookeeper_install,zookeeper_config
  needs: ["check zk test config"]
  rules:
    - if: $CI_COMMIT_BRANCH == "test"
      when: manual

deploy clickhouse in TEST:
  extends: .deploy
  environment: prod
  stage: clickhouse
  variables:
    ROLE_TAGS: clickhouse_install,clickhouse_config
  needs: ["check ch test config"]
  rules:
    - if: $CI_COMMIT_BRANCH == "test"
      when: manual

deploy haproxy in TEST:
  extends: .deploy
  environment: prod
  stage: haproxy
  variables:
    ROLE_TAGS: haproxy_install,haproxy_config
  needs: ["check haproxy test config"]
  rules:
    - if: $CI_COMMIT_BRANCH == "test"
      when: manual

deploy keepalived in TEST:
  extends: .deploy
  environment: prod
  stage: keepalived
  variables:
    ROLE_TAGS: keepalived_install,keepalived_config,keepalived_exporter
  needs: ["check keepalived test config"]
  rules:
    - if: $CI_COMMIT_BRANCH == "test"
      when: manual

# ############# deploy Exporters ######################################################

node exporter:
  stage: exporters
  image: ${AIND}
  script:
    - ansible-playbook -i inventories/${DEPLOY_ENV}/hosts clickhouse_infra.yml -u ${SSH_LOGIN} --tags=${ROLE_TAGS} -e VAULT_ADDR=${VAULT_ADDR} -e "VAULT_TOKEN=${VAULT_TOKEN}" --diff
  variables:
    ROLE_TAGS: node_exporter
  allow_failure: false
  environment: prod
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual
      
node exporter test:
  stage: exporters
  image: ${AIND}
  script:
    - ansible-playbook -i inventories/${DEPLOY_ENV}/hosts clickhouse_infra.yml -u ${SSH_LOGIN} --tags=${ROLE_TAGS} -e VAULT_ADDR=${VAULT_ADDR} -e "VAULT_TOKEN=${VAULT_TOKEN}" --diff
  variables:
    ROLE_TAGS: node_exporter
  allow_failure: false
  environment: prod
  rules:
    - if: $CI_COMMIT_BRANCH == "test"    
      when: manual
