variables: 
  AIND: git-registry.service.t1-cloud.ru/sre/docker/ansible:${ANSIBLE_TAG}
  ANSIBLE_TAG: latest
  ANSIBLE_FORCE_COLOR: 'true'
  DEPLOY_ENV: 't1-p1'
  ROLE_TAGS: 'all'
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: $CI_COMMIT_TAG
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

stages:
#  - ansible_lint
  - check_mode
  - zookeeper
  - clickhouse
  - haproxy
  - keepalived

.vault: &vault
  - export VAULT_ADDR=${VAULT_ADDR}
  - export VAULT_TOKEN=${VAULT_TOKEN}
  - vault status

.ssh: &ssh
  - mkdir -p ~/.ssh
  - touch ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - chmod 700 ~/.ssh
  - eval $(ssh-agent -s)
  - chmod 400 "$SRE_ADMIN_KEY"
  - ssh-add "$SRE_ADMIN_KEY"
#  - cp "$SSH_KNOWN_HOSTS" ~/.ssh/known_hosts
  - ssh-keyscan 10.13.248.51 10.13.248.52 10.13.248.53 > ~/.ssh/known_hosts

before_script:
  - ansible -m debug -a 'var=ansible_playbook_python' localhost
  - *ssh
  - date
  - *vault

check_roles:
  image: ${AIND}
  stage: check_mode
  script:
    - ansible-playbook -i inventories/${DEPLOY_ENV}/hosts clickhouse_infra.yml -u ${SSH_LOGIN} --tags=${ROLE_TAGS} -e VAULT_ADDR=${VAULT_ADDR} -e "VAULT_TOKEN=${VAULT_TOKEN}" --check -vv --diff
  allow_failure: true
  when: manual  
################ Deploy HA Clickhouse cluster ####################

.deploy:
  image: ${AIND}
  script:
    - ansible-playbook -i inventories/${DEPLOY_ENV}/hosts clickhouse_infra.yml -u ${SSH_LOGIN} --tags=${ROLE_TAGS} -e VAULT_ADDR=${VAULT_ADDR} -e "VAULT_TOKEN=${VAULT_TOKEN}" --diff
  allow_failure: false
  when: manual  
  
zookeeper:
  extends: .deploy
  stage: zookeeper
  variables:
    ROLE_TAGS: zookeeper_install,zookeeper_config

clickhouse:
  extends: .deploy
  stage: clickhouse
  variables:
    ROLE_TAGS: clickhouse_install,clickhouse_config

haproxy:
  extends: .deploy
  stage: haproxy
  variables:
    ROLE_TAGS: haproxy_install,haproxy_config

keepalived:
  extends: .deploy
  stage: keepalived
  variables:
    ROLE_TAGS: keepalived_install,keepalived_config

clickhouse_remove:
  extends: .deploy
  stage: clickhouse
  variables:
    ROLE_TAGS: remove
  only:
    variables:
    - $clickhouse_remove == "true"