---

repository_source: external

# Java
java_version: "19"
java_minior_version: "19.0.2"
jdk_source: "https://download.oracle.com/java/{{ java_version }}/latest/jdk-{{ java_version }}_linux-x64_bin.tar.gz"
jdk_proxy_source: ''
jdk_dir: /opt

# Zookeeper 
zookeeper_source: "https://dlcdn.apache.org/zookeeper/zookeeper-{{ zookeeper_version }}/apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz"
zookeeper_proxy_source: ''
zookeeper_version: "3.8.1"
zookeeper_dir: /opt/zookeeper
zookeeper_data_dir: /var/zookeeper
zookeeper_conf_dir: /etc/zookeeper
zookeeper_log_dir: /var/log/zookeeper
zookeeper_log_file: zookeeper.log
zookeeper_log_level: INFO
zookeeper_log_max_file_size: 265MB
zookeeper_log_max_backup_index: 20
zookeeper_client_port: 2181
zookeeper_init_limit: 5
zookeeper_sync_limit: 2
zookeeper_tick_time: 2000
zookeeper_global_outstanding_limit: 1000
zookeeper_prealloc_size: 64M
zookeeper_snap_count: 100000
zookeeper_max_client_cnxns: 10
zookeeper_min_session_timeout: "{{ 2 * zookeeper_tick_time }}"
zookeeper_max_session_timeout: "{{ 20 * zookeeper_tick_time }}"
zookeeper_autopurge_snapretain_count: 10
zookeeper_purge_interval: 1
zookeeper_fsync_warning_threshold_ms: 1000
zookeeper_members: "{{ groups['clickhouse'] | map('extract', hostvars, 'ansible_default_ipv4') | map(attribute='address') | list }}"
zookeeper_member_id: "{{ ansible_default_ipv4.address }}"
zookeeper_server_username: zookeeper-server
zookeeper_server_password: P@$$w0rd
zookeeper_clients:
  - username: zk_test
    password: P@$$w0rd
zookeeper_jmx_host: 127.0.0.1
zookeeper_jmx_port: 9181
zookeeper_jmx_rmi_port: 9182
zookeeper_jmx_username: zookeeper-jmx
zookeeper_jmx_password: P@$$w0rd
zookeeper_jmx_role: readonly
zookeeper_4lw_commands_whitelist: srvr,stat,mntr
zookeeper_heap_size: 1024
zookeeper_metrics_provider: true
