---
# Enabling the resolv.conf configuration.
general_dns_resolv_enabled: false
# Enabling DNS configuration via nsupdate.
general_dns_nsupdate_enabled: true
# DNS server for running nsupdate.
general_dns_nsupdate_server: '{{ general_dns_servers | first }}'

# Search paths that will be written to resolv.conf
general_dns_search:
  - test.01.vmw.t1.loc
# Nameservers that will be written to resolv.conf
general_dns_servers:
  - 10.13.8.1
  - 10.13.8.2

# The host from which nsupdate is running.
general_dns_managing_server: localhost
# TTL DNS records.
general_dns_ttl: 600

# The name of the key to run nsupdate.
general_dns_key_name: ''
# The secret key to run nsupdate.
general_dns_key_secret: ''
# The secret key algorithm.
general_dns_key_algorithm: ''
