---
- name: restart keepalived
  systemd:
    name: keepalived
    state: restarted
    daemon_reload: true
  when:
    - not ansible_check_mode

- name: reload keepalived
  systemd:
    name: keepalived
    state: reloaded
  when:
    - not ansible_check_mode
