---
haproxy_packet_name: haproxy

haproxy_global_raw_options:
  - stats socket /var/lib/haproxy/stats mode 660 level admin expose-fd listeners
  - stats timeout 30s

haproxy_frontend:
  - name: clickhouse_tcp
    bind:
      - listen: "0.0.0.0:{{ ch_frontend_tcp_port }}"
    mode: tcp
    default_backend: clickhouse-tcp
  - name: clickhouse_http
    bind:
      - listen: "{{ keepalived_lb_vip }}:{{ ch_frontend_http_port }}"
    mode: http
    default_backend: clickhouse-http

haproxy_listen:
  - name: stats
    description: Global statistics
    bind:
      - listen: 0.0.0.0:8404
    mode: http 
    stats:
      enable: true
      refresh: 10s 

haproxy_backend:
  - name: clickhouse-tcp
    mode: tcp
    balance: roundrobin
    server:
      - name: dc1-v-clickhouse001
        listen: 10.13.248.51:9000
        param:
          - check
      - name: dc1-v-clickhouse002
        listen: 10.13.248.52:9000
        param:
          - check
          - backup
      - name: dc1-v-clickhouse003
        listen: 10.13.248.53:9000
        param:
          - check
          - backup
  - name: clickhouse-http
    mode: http
    balance: roundrobin
    server:
      - name: dc1-v-clickhouse001
        listen: 10.13.248.51:8123
        param:
          - check
      - name: dc1-v-clickhouse002
        listen: 10.13.248.52:8123
        param:
          - check
          - backup
      - name: dc1-v-clickhouse003
        listen: 10.13.248.53:8123
        param:
          - check
          - backup